#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

message="$(cat "$1")"
requiredPattern="^:(art|zap|fire|bug|ambulance|sparkles|memo|rocket|lipstick|tada|white_check_mark|lock|closed_lock_with_key|bookmark|rotating_light|construction|green_heart|arrow_down|arrow_up|pushpin|construction_worker|chart_with_upwards_trend|recycle|heavy_plus_sign|heavy_minus_sign|wrench|hammer|globe_with_meridians|pencil2|poop|rewind|twisted_rightwards_arrows|package|alien|truck|page_facing_up|boom|bento|wheelchair|bulb|beers|speech_balloon|card_file_box|loud_sound|mute|busts_in_silhouette|children_crossing|building_construction|iphone|clown_face|egg|see_no_evil|camera_flash|alembic|mag|label|seedling|triangular_flag_on_post|goal_net|dizzy|wastebasket|passport_control|adhesive_bandage|monocle_face|coffin|test_tube|necktie|stethoscope|bricks|technologist|money_with_wings|thread|safety_vest): .+$"
if ! echo "$message" | grep -qE "$requiredPattern";
then
  echo "------------------------------------------"
  echo "🚨 Wrong commit message!"
  echo "The commit message must have this format:"
  echo ":emoji: <message>"
  echo "Allowed emojis with their meanings are available at https://gitmoji.dev/"
  echo "Example: \":art: Improve the design\""
  echo "-"
  echo "Your commit message was:"
  echo "$message"
  echo "-"
  echo "For more information, check script in .husky/commit-msg"
  echo "-"
  exit 1
fi